version: '3.4'

services:
  database.service:
    image: ${DOCKER_REGISTRY-}databaseservice
    container_name: database-service
    hostname: database-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 443:443
    networks:
      - database-network
  database:
    image: mongo:latest
    container_name: database
    hostname: database
    expose:
      - "27017"
    ports:
      - 27017:27017
    networks:
      - database-network
    volumes:
      - ~/mongodb/data:/data/db
    restart: always
    entrypoint: /usr/bin/mongod --bind_ip_all --wiredTigerCacheSizeGB 0.25 #--replSet rstest
  # mongosetup:
  #   image: mongo:latest
  #   container_name: mongosetup
  #   hostname: mongosetup
  #   depends_on:
  #     - database
  #   networks:
  #     - database-network
  #   restart: "no"
  #   command: >
  #     mongosh --host database:27017 --eval
  #     '
  #     config = {
  #       "_id" : "rstest",
  #       "version": 1,
  #       "members" : [
  #         {
  #           "_id" : 1,
  #           "host" : "database:27017"
  #         }
  #       ]
  #     };
  #     rs.initiate(config);
  #     '
networks:
  database-network:
    driver: bridge

#https://www.mongodb.com/docs/drivers/go/current/fundamentals/connection/#connect-to-a-replica-set
#mongodb://localhost:27017/?replicaSet=rstest&directConnection=true